apiVersion: v1
kind: LimitRange
metadata:
  name: baixo-recurso
spec:
  limits:
  - default:
      cpu: "1"
      memory: "128Mi"
    defaultRequest:
      cpu: "0.5"
      memory: "100Mi"
    type: Container
