kind: PersistentVolume
apiVersion: v1
metadata:
  name: meu-vol
  labels:
    type: local
spec:
  capacity:
    storage: 100M
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/giropops
    server: 10.142.0.2
    readOnly: false
